### ISSUE TITLE
Relase comment from tag comment

### ISSUE THREAD

**Issue by fnagel** [NamelessCoder/gizzle-typo3-plugins#2]
Is it possible to grab the commit message from the tag and use it as the TER release comment?

**Comment by NamelessCoder** [comment]
There's actually already an open request for that and I think @PowerKiKi might be looking into that. The issue got misplaced so it's very easily missed - the link is: https://github.com/FluidTYPO3/fluidtypo3-gizzle/issues/3.

**Comment by PowerKiKi** [comment]
Hey, I am not working on anything right now. I have other things planned for the coming days, so feel free to start if you are in a hurry.

I'll come back check, and report, here if/when anything happen...

**Comment by fnagel** [comment]
Thanks for you fast answers!

I pretty busy myself at the moment but this is something I really want for my private projects -- as it would save me so much time! Will see if there's a little time next few days...

Would you mind giving me a little hint on how to do this? I guess I will need to change something around here: https://github.com/NamelessCoder/gizzle-typo3-plugins/blob/master/src/NamelessCoder/GizzleTYPO3Plugins/GizzlePlugins/ExtensionRepositoryReleasePlugin.php#L53-L77

Any idea on how to get the tags commit message?

**Comment by NamelessCoder** [comment]
Check that out, @fnagel - it was an extremely simple matter to use another value as default, so now you can simply remove the `comment` setting and the message will be grabbed from Payload HEAD's commit message.

**Comment by NamelessCoder** [comment]
FYI for both of you guys (and @PowerKiKi if you'd pass it along to Fabien that'd be great): I have updated the `fluidtypo3-gizzle` repository to set the upload comment as per the description in commit. If you're using this as base for your forks don't forget to remove the comment setting if you want it to be taken from Payload HEAD.

**Comment by fnagel** [comment]
@NamelessCoder Wow, that was fast. Thank you very much!

**Comment by fnagel** [comment]
Just wanted to give some feedback as I finally found some time to tests this in the real world: works like a charm. Just had some minor issues with the GitCommandResolver (as I'm using toast to have multiple git installations available).

My first automated release: http://typo3.org/extensions/repository/view/t3extblog

**Comment by NamelessCoder** [comment]
Hi Felix - about the GitCommandResolver, we could add a configuration option to all the Gizzle Git plugins to set the Git executable path and only ask the GitCommandResolver if that option is not set. I neglected to consider the case of multiple Git binaries and went for the `which` solution that works so well in normal CLI ;)

**Comment by fnagel** [comment]
Hey Claus, that would solve the case for me without changing the resolver. 

Anyway, when using `which` as PHP user it does work but not when the hook is actually called via GitHub. I already asked by admin why thats the case.

**Comment by NamelessCoder** [comment]
That was easier done than said: https://github.com/NamelessCoder/gizzle-git-plugins/commit/a003a9399ce8c03d0fd760d2014370f19cc391bc

;)

**Comment by fnagel** [comment]
Nice! Can you explain where to put this config?

Tried something like this in my fluidtypo3-gizzle\settings\ExtensionRelease.yml
````
NamelessCoder\GizzleTYPO3Plugins:
  NamelessCoder\GizzleTYPO3Plugins\GizzlePlugins\ExtensionRepositoryReleasePlugin:
    enabled: true
    directory: /var/my-path/gizzle/tmp

NamelessCoder\GizzleGitPlugins:
  NamelessCoder\GizzleGitPlugins\GizzlePlugins\ClonePlugin:
    gitCommand: /var/my-path/bin/git
  NamelessCoder\GizzleGitPlugins\GizzlePlugins\PullPlugin:
    gitCommand: /var/my-path/bin/git
````
but without success.

ps: SelfUpdate.yml won't work for me as there is another "which git" command.

**Comment by NamelessCoder** [comment]
Hi Felix,

Ah yes of course... `ExtensionRepositoryReleasePlugin` will control those parameters and ignore those you set in the settings - because the `ClonePlugin` is not used as a "root plugin".

This tells me there should be two additional iterations that I'll be creating momentarily:

1. It should be possible to configure/override the settings of plugins used this way, as sub-definitions under the main plugin.
2. The `ExtensionRepositoryRelease` command itself should have a `gitCommand` option that gets transferred to the sub-plugin.

I'll add the same `gitCommand` option to the `SelfUpdatePlugin` ;)

**Comment by fnagel** [comment]
Ok, I will wait for an update an try again. Thanks for your support!

**Comment by NamelessCoder** [comment]
Step one: https://github.com/NamelessCoder/gizzle/commit/6006f0502fc849b7752d2e4257c7762a65160c28

(released as namelesscoder/gizzle 1.6.0)

**Comment by NamelessCoder** [comment]
Step two: https://github.com/NamelessCoder/gizzle/commit/228d7c990db4b69775049ec7d565262fa366409c

(released as namelesscoder/gizzle 1.6.1)

(yeah, the iterative thing is taken maybe a bit too seriously hehe)

**Comment by NamelessCoder** [comment]
Step three: https://github.com/NamelessCoder/gizzle-git-plugins/commit/7c476db81b58bed7dc769866491b2adb6ddb19bb

(namelesscoder/gizzle-git-plugins:0.1.7)

Mainly to introduce a constant that can be relied on for default git command also in other plugins that depend on this one, e.g. `ExtensionRepositoryReleasePlugin`.

**Comment by NamelessCoder** [comment]
And step four: https://github.com/NamelessCoder/gizzle-typo3-plugins/commit/b2804a8c0758a3ac4826e9a4f269e1be0b6ddc9f

(namelesscoder/gizzle-typo3-plugins:1.2.0)

Last thing to do is update dependencies for this package and everything should fall into place.

**Comment by NamelessCoder** [comment]
Ready to roll, I hope :) let me know if anything fails. Your average *nix install should allow the backtick command usage.

**Comment by fnagel** [comment]
All changes work as expected. Thanks!

Not sure if the selfUpdate works. The Hook seems to work and so does the git pull but I'm not sure of the composer command. I will check this again and give more feedback.

**Comment by NamelessCoder** [comment]
If you're still using the fork of `fluidtypo3-gizzle` you should rebase - the `composer.lock` is included and unless that's updated (I do that manually) you'll be getting some old dependencies on a plain `composer install`.

**Comment by fnagel** [comment]
I noticed that., but rebase onto what? The composer.lock file is still included in `fluidtypo3-gizzle`. I thought about removing that file from my fork.

**Comment by NamelessCoder** [comment]
I suppose a `git pull upstream --rebase` will do it, assuming you added the fork's upstream as `upstream`. I do that to my own repositories.

**Comment by NamelessCoder** [comment]
Btw, if you don't use the formalities plugin then you could just kickstart a fresh `gizzle` project, symlink the `web/index.php` file like in https://github.com/FluidTYPO3/fluidtypo3-gizzle/tree/master/web, add your own configuration file and then never have to worry about the `fluidtypo3-gizzle` repository.
